name: Testing

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  run-server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Start Express.js Server
        run: node backend.js &

  test-with-curl:
    runs-on: ubuntu-latest
    needs: run-server # Ensure run-server job completes first

    steps:
      - name: Wait for Server to Start
        run: sleep 10s # Adjust if your server takes longer to start

      - name: Test with curl
        run: |
          curl -i http://localhost:8080/persons
